version: '2'

services:
   db:
     env_file: ./env/wordpress.env
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
   wordpress:
     env_file: ./env/db.env
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wordpress/themes:/var/www/html/wp-content/themes
     ports:
       - "8000:80"
     restart: always
  web:
    image: abiosoft/caddy
    restart: always
    environment:
      CADDYPATH: "/etc/caddycerts"
    volumes:
      - ./conf/Caddyfile:/etc/Caddyfile
      - caddy-certs:/etc/caddycerts
      - caddy-web:/srv
    ports:
      - "80:80"
      - "443:443"

volumes:
    db_data:
