version: '2'

services:
   db:
     env_file: ./env/wordpress.env
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
   wordpress:
     env_file: ./env/db.env
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
volumes:
    db_data:
