import { h } from 'preact';
import styles from './About.scss';

const About = () => (
    <section className={styles.About}>
        <h1>About</h1>
        <p>
           Lorem Khaled Ipsum is a major key to success. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. Let me be clear, you have to make it through the jungle to make it to paradise, that’s the key, Lion! They don’t want us to win. Congratulations, you played yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. Watch your back, but more importantly when you get out the shower, dry your back, it’s a cold world out there. Hammock talk come soon. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. To succeed you must believe. When you believe, you will succeed. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel.
        </p>
        <p>
           Lorem Khaled Ipsum is a major key to success. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. Let me be clear, you have to make it through the jungle to make it to paradise, that’s the key, Lion! They don’t want us to win. Congratulations, you played yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. Watch your back, but more importantly when you get out the shower, dry your back, it’s a cold world out there. Hammock talk come soon. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. To succeed you must believe. When you believe, you will succeed. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel.
        </p>
        <p>
           Lorem Khaled Ipsum is a major key to success. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. Let me be clear, you have to make it through the jungle to make it to paradise, that’s the key, Lion! They don’t want us to win. Congratulations, you played yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. Watch your back, but more importantly when you get out the shower, dry your back, it’s a cold world out there. Hammock talk come soon. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. To succeed you must believe. When you believe, you will succeed. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel.
        </p>
        <p>
           Lorem Khaled Ipsum is a major key to success. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. Let me be clear, you have to make it through the jungle to make it to paradise, that’s the key, Lion! They don’t want us to win. Congratulations, you played yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. Watch your back, but more importantly when you get out the shower, dry your back, it’s a cold world out there. Hammock talk come soon. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. To succeed you must believe. When you believe, you will succeed. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel.
        </p>
        <p>
           Lorem Khaled Ipsum is a major key to success. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. Let me be clear, you have to make it through the jungle to make it to paradise, that’s the key, Lion! They don’t want us to win. Congratulations, you played yourself. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. Watch your back, but more importantly when you get out the shower, dry your back, it’s a cold world out there. Hammock talk come soon. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. The first of the month is coming, we have to get money, we have no choice. It cost money to eat and they don’t want you to eat. To succeed you must believe. When you believe, you will succeed. Put it this way, it took me twenty five years to get these plants, twenty five years of blood sweat and tears, and I’m never giving up, I’m just getting started. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel.
        </p>
    </section>
);

export default About;
